# Generated by Django 5.0.6 on 2024-06-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('razao_social', models.CharField(max_length=256, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('ramo', models.CharField(max_length=128, verbose_name='Ramo de Atuação')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('fone', models.CharField(blank=True, max_length=15, verbose_name='fone')),
                ('tem_zap', models.BooleanField(default=False, verbose_name='Tem Whatsapp?')),
                ('cnae_principal', models.CharField(max_length=256, verbose_name='CNAE Principal')),
                ('cnae_secundario', models.TextField(max_length=1024, verbose_name='CNAE Principal')),
                ('bairro', models.CharField(blank=True, max_length=64, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=64, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
            ],
            options={
                'verbose_name': 'Empresa',
            },
        ),
    ]
