# Generated by Django 5.0.6 on 2024-06-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas', '0003_alter_empresa_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
    ]
