# Generated by Django 5.0.6 on 2024-06-07 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telas', '0002_alter_empresa_cnae_principal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospeccao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('msg_enviada', models.BooleanField(default=False, verbose_name='Mensagem Enviada?')),
                ('cliente_respondeu', models.BooleanField(default=False, verbose_name='Cliente respondeu?')),
                ('indicado', models.BooleanField(default=False, verbose_name='Foi indicado?')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telas.empresa')),
            ],
            options={
                'verbose_name': 'Prospecçoes',
            },
        ),
    ]
