# Generated by Django 5.0.6 on 2024-06-07 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospeccoes', '0001_initial'),
        ('telas', '0002_alter_empresa_cnae_principal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prospeccao',
            options={'verbose_name': 'Prospecçõe'},
        ),
        migrations.AddField(
            model_name='prospeccao',
            name='comentarios',
            field=models.TextField(default='', verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='prospeccao',
            name='empresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='telas.empresa'),
        ),
    ]
